# Generated by Django 6.0 on 2025-12-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_email_alter_paciente_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Ej: Penicilina', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='hipertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones_medicas',
            field=models.TextField(blank=True, help_text='Antecedentes relevantes', null=True),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='tratamientos/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='firma',
            field=models.TextField(),
        ),
    ]
