# Generated by Django 6.0 on 2025-12-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_alergias_paciente_diabetes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='observaciones_medicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
