# Generated by Django 5.2.8 on 2025-12-31 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_fotogaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tratamientos_extra/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_tratamiento', to='pacientes.tratamiento')),
            ],
        ),
    ]
