# Generated by Django 5.2.8 on 2026-01-02 03:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_paciente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
